- README.md
Just some minor improvements on the wording in the README file
> Fix some wording in the README.md

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/Rotation.kt
Added a working gcd patch & fixed spelling mistake
> Patched gcd

- 1.8.9-Forge/.gitignore
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/injection/forge/mixins/gui/MixinGuiButton.java
Fix Slider Texture in the Music & Sounds screen by binding the button texture + adding .idea folder to .gitignore because gay
> Fix Slider Texture in the Music & Sounds screen

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/LiquidBounce.java
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/CommandManager.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/Shortcut.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/ReloadCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/ScriptManagerCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/ShortcutCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/Module.java
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/ModuleManager.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/ui/client/GuiScripts.kt
Beautified some code in ModuleManager.kt and CommandManager.kt.
Also made basic shortcuts impl, but without serialization (see https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3255)
> Beautify ModuleManager.kt and CommandManager.kt, command shortcuts impl.

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/ui/client/altmanager/GuiAltManager.java
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/ui/client/altmanager/sub/reconnect/GuiFritzBoxReconnect.kt
I tried it with Fritz!Box 7362SL.
> Fritz!Box reconnect feature

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/ui/client/altmanager/GuiAltManager.java
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/ui/client/altmanager/sub/GuiSessionLogin.kt
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2771
> Added Session Login in Altmanager

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/ui/font/FontRenderer.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/ui/font/GameFontRenderer.kt
> Improved font renderer

- 1.8.9-Forge/gradle.properties
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/render/shader/shaders/OutlineShader.java
- 1.8.9-Forge/src/main/resources/assets/minecraft/liquidbounce/shader/fragment/glow.frag
- 1.8.9-Forge/src/main/resources/assets/minecraft/liquidbounce/shader/fragment/outline.frag
- 1.8.9-Forge/src/main/resources/assets/minecraft/liquidbounce/shader/vertex.vert
> Fix Glow & Outline on AMD.

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/combat/AutoArmor.java
I made a misstake when reworking AutoArmor. Fixes CCBlueX/LiquidBounce1.8-Issues#3399
> Fixed wrong value order

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/injection/forge/mixins/client/MixinMinecraft.java
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/ui/client/hud/element/elements/Text.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/CPSCounter.java
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/RollingArrayLongBuffer.java
You can now use `%cps%` (alias for `%lcps%`; Left button), `%mcps%` (Middle mouse button), `%rcps%` (Right mouse button)
Fixes CCBlueX/LiquidBounce1.8-Issues#3404
> Added %cps% options to the CustomGUI

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/ModuleManager.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/exploit/UnSaddledRide.java
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/injection/forge/mixins/entity/MixinEntityHorse.java
- 1.8.9-Forge/src/main/resources/liquidbounce.forge.mixins.json
Allows to ride a horse without a saddle.
Fixes CCBlueX/LiquidBounce1.8-Issues#3393
> Added new Module: UnSaddledRide

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/SettingsUtils.java
Cleaned up code in `SettingsUtils.java` and removed the restriction to render modules in SettingsUtils.executeScript
Fixes CCBlueX/LiquidBounce1.8-Issues#3385
> Auto settings update

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/combat/AutoBow.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/combat/BowAimbot.kt
Fixes CCBlueX/LiquidBounce1.8-Issues#2624
> Added WaitForBowAimbot option to AutoBow

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/item/ArmorComparator.java
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/item/ItemUtils.java
- Fixes CCBlueX/LiquidBounce1.8-Issues#3453
- Fixes CCBlueX/LiquidBounce1.8-Issues#3457
> Added AutoArmor comparision thresholds.

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/ui/client/altmanager/GuiAltManager.java
Fixes CCBlueX/LiquidBounce1.8-Issues#3380
> Made AltManager select the alt you are logged in with

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/Command.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/CommandManager.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/AutoSettingsCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/BindCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/EnchantCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/FriendCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/GiveCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/HClipCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/HoloStandCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/HurtCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/LocalAutoSettingsCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/PanicCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/PingCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/ReloadCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/RemoteViewCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/RenameCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/SayCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/ScriptManagerCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/ServerInfoCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/ShortcutCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/TacoCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/TargetCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/ToggleCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/UsernameCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/VClipCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/ModuleCommand.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/injection/forge/mixins/gui/MixinGuiChat.java
Add command tab completion
This partially closes https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3372 but still requires the  semi-opaque suggestion based on the provided arguments, but I don't think I will add that myself.
> Add command tab completion

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/CommandManager.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/injection/forge/mixins/gui/MixinGuiChat.java
Fixes CCBlueX/LiquidBounce1.8-Issues#3372
> Fixed crash when trying autocomplete a finished command

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/player/InventoryCleaner.kt
Fixes CCBlueX/LiquidBounce1.8-Issues#3465
> Fixed a bug where InvCleaner doesn't replace an item with a water bucket 

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/player/InventoryCleaner.kt
Fixes CCBlueX/LiquidBounce1.8-Issues#3462
> Fixed a bug where InvCleaner drops useful items

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/injection/forge/mixins/network/MixinNetworkPlayerInfo.java
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/injection/forge/mixins/resources/MixinSkinManager.java
- 1.8.9-Forge/src/main/resources/liquidbounce.forge.mixins.json
Closes CCBlueX/LiquidBounce1.8-Issues#3166
> Made SkinProtect protect TabGui faces and skulls

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/player/InventoryCleaner.kt
Fixes CCBlueX/LiquidBounce1.8-Issues#3469
> Fixed a bug where ChestStealer doesn't take tools

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/render/StorageESP.java
Fixes CCBlueX/LiquidBounce1.8-Issues#3470
> Reset the color after rendering StorageESP Outlines

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/injection/forge/mixins/gui/MixinGuiDisconnect.java
Fixes CCBlueX/LiquidBounce1.8-Issues#3074
Closes CCBlueX/LiquidBounce1.8-Issues#3490
> Made "Random alt" button show "New TheAltening alt" when an api key is loaded

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/combat/Criticals.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/movement/Fly.java
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/world/Tower.java
Contains criticals, damage fly and tower for hypixel.
> Hypixel Bypasses

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/extensions/PlayerExtension.kt
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3517
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3517#issuecomment-583727077
(i guess it needs a beautify)
> implemented afterys Distance calc

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/injection/forge/mixins/entity/MixinAbstractClientPlayer.java
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/injection/forge/mixins/network/MixinNetworkPlayerInfo.java
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/injection/forge/mixins/resources/MixinSkinManager.java
Fixes CCBlueX/LiquidBounce1.8-Issues#3516
> Fixed NPEs when having SkinProtect enabled

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/GiveCommand.kt
Fixes CCBlueX/LiquidBounce1.8-Issues#3504
> Fixed .give + made it prefer the hotbar

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/misc/AntiBot.java
made antibot livingtime changeable
kinda
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3368
> made antibot livingtime changeable

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/InventoryUtils.java
A lot of minigames have auto fusing tnt and its not useful for scaffold so its need blacklicted too for that
> Added Tnt to BlackList

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/player/NoFall.java
Closes CCBlueX/LiquidBounce1.8-Issues#3615
> Updated hypixel nofall (no bans)

- .github/CODING_STANDARDS.md
This file has been created to document the coding process of the LiquidBounce codebase in a standards _.md_ document. Feel free to edit.
> Created CODING_STANDARDS.md

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/player/InventoryCleaner.kt
> Added IgnoreVehicle option to keep vehicles in inventory

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/ModuleManager.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/combat/ReachAura.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/injection/forge/mixins/entity/MixinEntityPlayerSP.java
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/PathUtils.java
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/astar/Astar.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/astar/NaiveAstarFlyNode.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/astar/NaiveAstarGroundNode.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/astar/NaiveAstarNode.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/block/BlockUtils.kt
A sometimes glitchy module ReachAura(TpAura or InfiniteAura). Only for vanilla servers.
> Added ReachAura

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/misc/Teams.kt
added "GommeSW" value to "Teams"
> fixed CCBlueX/LiquidBounce1.8-Issues#3059

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/render/ESP.java
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/render/WorldToScreen.java
Closes CCBlueX/LiquidBounce1.8-Issues#3723
> Real 2D-ESP

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/ModuleCommand.kt
Fixes CCBlueX/LiquidBounce1.8-Issues#3533
> Improved ModuleCommand

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/combat/AutoSoup.kt
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3747
> Added bowl options for autosoup

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/player/Regen.kt
Closes CCBlueX/LiquidBounce1.8-Issues#3673
> Added PotionEffect option to Regen

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/render/HeadRotations.kt
- fixed NullPointerException
- fixed ClassCastException
- removed useless semicolons
> Fixed HeadRotations Exceptions

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/player/AntiAFK.kt
- added old mode
- added random mode
- added custom mode
- cleanup code
> Improved AntiAFK

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/render/Tracers.kt
- Added "Custom" color mode
- Changed "DistanceColor" Boolean to a List option
- Added "Rainbow" color mode
- Added RGB-Slider
closes CCBlueX/LiquidBounce1.8-Issues#2670
> Added ColorModes to Tracers

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/misc/NameProtect.java
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/injection/forge/mixins/gui/MixinGuiChat.java
- added text hint to chat
closes CCBlueX/LiquidBounce1.8-Issues#3796
- fixed a bug, where the autocomplete start not with the first index
fixes CCBlueX/LiquidBounce1.8-Issues#3795
> Improved AutoCompletion & Fixed Friend Alias bug

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/player/FastUse.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/file/configs/AccountsConfig.java
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/file/configs/FriendsConfig.java
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/injection/forge/mixins/gui/MixinGuiDisconnected.java
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/ui/client/altmanager/GuiAltManager.java
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/ui/client/altmanager/sub/GuiAdd.java
closes CCBlueX/LiquidBounce1.8-Issues#3745
> Rework Friends & accounts config

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/player/InventoryCleaner.kt
usedButton 4 is impossible to achieve legitimately
> Fixed bug that caused instabans

- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/render/ESP.java
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/injection/forge/mixins/client/MixinMinecraft.java
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/injection/forge/mixins/world/MixinChunk.java
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/ui/client/hud/HUD.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/ui/client/hud/element/Element.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/ui/client/hud/element/elements/Radar.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/render/MiniMapRegister.kt
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/render/RenderUtils.java
- 1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/render/SafeVertexBuffer.java
Closes CCBlueX/LiquidBounce1.8-Issues#2866
> Add Radar Element to CustomHUD

- shared/main/java/net/ccbluex/liquidbounce/features/module/modules/combat/KillAura.kt
now also takes into account the changes in player position
> Improved (?) Prediction for KillAura

- shared/main/java/net/ccbluex/liquidbounce/features/module/modules/exploit/Phase.java
> fixed MinePlex Phase

- shared/main/java/net/ccbluex/liquidbounce/features/command/CommandManager.kt
- shared/main/java/net/ccbluex/liquidbounce/features/command/special/BlockBlacklistCommand.kt
- shared/main/java/net/ccbluex/liquidbounce/features/command/special/ChatAdminCommand.kt
- shared/main/java/net/ccbluex/liquidbounce/features/command/special/ChatTokenCommand.kt
- shared/main/java/net/ccbluex/liquidbounce/features/command/special/LiquidChatCommand.kt
- shared/main/java/net/ccbluex/liquidbounce/features/command/special/PrivateChatCommand.kt
- shared/main/java/net/ccbluex/liquidbounce/features/command/special/XrayCommand.kt
- shared/main/java/net/ccbluex/liquidbounce/features/module/modules/misc/LiquidChat.kt
- shared/main/java/net/ccbluex/liquidbounce/features/module/modules/render/XRay.kt
- shared/main/java/net/ccbluex/liquidbounce/features/special/ClientRichPresence.kt
- changed some module specific commands to have a better overview
> Updated Commands

- shared/main/java/net/ccbluex/liquidbounce/features/module/modules/world/Scaffold.java
* Includes Scaffold AutoBlock fixes from this [pull request.](https://github.com/CCBlueX/LiquidBounce/pull/159)
* Updated version of this [one](https://github.com/CCBlueX/LiquidBounce-Issues/issues/3913) and this [one.](https://github.com/CCBlueX/LiquidBounce/pull/163) `9/23/2020`
* It's from 1.8.9 code. (In case Marco or Senk Ju is wondering)
* Slow + SlowSpeed fixed. (In case again Marco or Senk Ju is wondering)
* AutoBlock + StayAutoBlock merged and are in 1 list + now there's a Switch mode, similar to LolMC's AutoFindBlock.
> Custom Scaffold Merge.

- shared/main/java/net/ccbluex/liquidbounce/features/module/modules/exploit/Phase.java
I probably don't know much about coding, but I come from a C/C+ background even though I don't know a lot about it, so I thought since the Mineplex mode is the only one which has "IsCollidedHorizontally" and the others didn't, why not change the others too, and it worked.
> Fixed a Phase bug.

- shared/main/java/net/ccbluex/liquidbounce/features/command/commands/RenameCommand.kt
- shared/main/java/net/ccbluex/liquidbounce/features/module/modules/movement/NoSlow.kt
Cleared redundant imports so that 1.12 could build
> fixed 1.12 build

- shared/main/java/net/ccbluex/liquidbounce/ui/client/hud/HUD.kt
- shared/main/java/net/ccbluex/liquidbounce/ui/client/hud/element/elements/SpeedGraph.kt
- shared/main/java/net/ccbluex/liquidbounce/ui/client/hud/element/elements/Speedmeter.kt
Added a SpeedGraph as HUD-Element
https://ibb.co/dfXx4j5
> SpeedGraph

- shared/main/java/net/ccbluex/liquidbounce/features/command/commands/ScriptManagerCommand.kt
* Fixes this [bug.](https://github.com/CCBlueX/LiquidBounce/issues/233)
> Fixed a .scriptmanager reload bug.

- shared/main/java/net/ccbluex/liquidbounce/features/module/modules/movement/Speed.kt
- shared/main/java/net/ccbluex/liquidbounce/features/module/modules/movement/speeds/other/Matrix.kt
* Added sliders for timer + speed values.
* Connected these values to the functions so that they would work.
> Matrix Speed improvements.

- README.md
just thought it needed to be explained
> Clarify supported versions

- shared/main/java/net/ccbluex/liquidbounce/features/module/modules/movement/speeds/other/Matrix.kt
* Improved its speed by a bit.
* Includes strafes.
> Improved Matrix Speed.

- shared/main/java/net/ccbluex/liquidbounce/features/module/modules/movement/Fly.kt
* Grants this [request.](https://github.com/CCBlueX/LiquidBounce/issues/282)
* Inspired by DuCouscous' [script.](https://liquidbounce.net/scripts/view?id=5fb122ed75cd4e1f7e0aaa94)
* Probably updates in the future..
> Added Redesky fly mode.

- README.md
not the same as my nextgen commit to do this
> Update Forums Link

- README.md
which idiot forgot to update this
> Update 'Issues' link in README

- shared/main/java/net/ccbluex/liquidbounce/features/module/modules/render/ESP.kt
- shared/main/java/net/ccbluex/liquidbounce/features/module/modules/render/ProphuntESP.kt
- shared/main/java/net/ccbluex/liquidbounce/features/module/modules/render/Tracers.kt
* Fixes a Tracers bug which shows a big line or a huge sized nametags, or something else.
* Renamed Prophunt's modes.
* Thanks to [this.](https://forums.ccbluex.net/topic/1089/help-pls-bag-bag-esp-menu-bugs-bugs/15)
> Fixed a Tracers bug + PropHunt small updates.

- shared/main/java/net/ccbluex/liquidbounce/features/module/modules/movement/Strafe.kt
* Has to do with [this.](https://github.com/CCBlueX/LiquidBounce/issues/322)
* Fixed that bug where you could not move.
* Renamed options.
> Fixed Strafe bugs.

- shared/main/java/net/ccbluex/liquidbounce/features/module/modules/world/Tower.kt
* Added the ability to return back to your previous slot automatically when you disable Tower.
* Added an AutoBlock mode.
> Tower Improvements.

- shared/main/java/net/ccbluex/liquidbounce/features/module/modules/combat/Velocity.kt
this can bypass newest AAC v4 and some other anticheat
> Add AACv4 velocity

- src/main/kotlin/net/ccbluex/liquidbounce/features/module/ModuleManager.kt
- src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/exploit/ModuleDamage.kt
- src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/exploit/ModuleGodMode.kt
- src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/movement/ModuleAutoWalk.kt
- src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/movement/ModuleNoClip.kt
- src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/player/ModuleAutoWalk.kt
AutoWalk: I would've also added the if statement `if (!mc.gameSettings.isKeyDown(mc.gameSettings.keyBindForward))` (1.8.9), but I didn't know how to code it the 1.16.5 way.
> More module addition.

- build.gradle
- src/main/kotlin/net/ccbluex/liquidbounce/native/Natives.kt
- src/main/kotlin/net/ccbluex/liquidbounce/renderer/ultralight/Ultralight.kt
- src/main/kotlin/net/ccbluex/liquidbounce/renderer/ultralight/screen/UltralightScreen.kt
- src/main/kotlin/net/ccbluex/liquidbounce/renderer/ultralight/support/ViewContextProvider.kt
Please fix the natives in the cloud. You can download the latest Ultralight SDK from here: https://github.com/ultralight-ux/Ultralight/blob/master/README.md#getting-the-latest-sdk
> Bumped ultralight-java's version to 0.4.1

- src/main/kotlin/net/ccbluex/liquidbounce/features/module/ModuleManager.kt
- src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/render/ModuleFullBright.kt
This PR adds a FullBright module. 
It should essentially work the same as the FullBright module from the current version of LiquidBounce.
> feat(module): FullBright

- 1.12.2-Forge/build.gradle
- 1.8.9-Forge/build.gradle
- shared/main/java/net/ccbluex/liquidbounce/features/module/modules/render/ESP.kt
- shared/main/java/net/ccbluex/liquidbounce/features/module/modules/render/StorageESP.kt
- shared/main/java/net/ccbluex/liquidbounce/utils/login/UserUtils.kt
> multi color support for shader mode
> multi storage support for shader mode (StorageESP)
> change org.json to gson in UserUtils
> Better ESP & Better Code

- src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/exploit/ModuleKick.kt
- src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/exploit/ModuleSleepWalker.kt
- src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/movement/ModuleFreeze.kt
add some info and removed some useless things
> add some info and removed some useless things 

- src/main/kotlin/net/ccbluex/liquidbounce/utils/aiming/PointTracker.kt
helps on 1.8 protocol since some anticheats will flag for hitbox even with it set to 0.1
note:
if you think im trying to get a free commit, you could try committing this yourself, idc
> increase maxium shrinkbox value

- src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/movement/noslow/modes/blocking/NoSlowBlock.kt
- src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/movement/noslow/modes/consume/NoSlowConsume.kt
- src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/movement/noslow/modes/shared/NoSlowSharedIntave14.kt
tested on mineblaze.net
this isnt slower than vanilla
> intave noslow

- src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/movement/noslow/modes/shared/NoSlowSharedIntave14.kt
> fix: intave noslow

- src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/movement/ModuleNoWeb.kt
- src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/movement/noslow/modes/blocking/NoSlowBlock.kt
- src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/movement/noslow/modes/blocking/NoSlowBlockIntave14.kt
- src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/movement/noslow/modes/consume/NoSlowConsume.kt
- src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/movement/noslow/modes/consume/NoSlowConsumeIntave14.kt
- src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/movement/noslow/modes/shared/NoSlowSharedIntave14.kt
> more intave bypasses

- src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/movement/noslow/modes/consume/NoSlowConsumeIntave14.kt
use Direction.UP instead of horizontal facing opposite or however that fucking was
> intave consume noslow fix
