CCBlueX/LiquidBounce

1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/movement/BugUp.kt
To make it possible to only setback when there is no block below. See CCBlueX/LiquidBounce1.8-Issues#3362
=> Bumped up max fall distance to 255

1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/combat/AutoArmor.java
Before this fix AutoArmor would wait for the delay, but if there are more than one update to perform it just ignores it.
Fixes CCBlueX/LiquidBounce1.8-Issues#3466
=> Fixed AutoArmor Delay Bug

1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/misc/AntiBot.java
DuplicateInWorld marks entities as bot when their names are in the loaded entity list more then once.
DuplicateInTab marks entities as bot when their name is in tab more then once.
=> Added 2 antibot modes

1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/combat/KillAura.kt
Allows KillAura to not rotate and hit entity.
In order to ignore rotations, you must set `maxTurnSpeed` value to `0`.
Fixes CCBlueX/LiquidBounce1.8-Issues#3547
=> KillAura improvements (can disable rotation)

1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/ReloadCommand.kt
CommandManager adds new and new script commands after every use of .reload
This causes LB to randomly crash, script commands to not work after reloading.
This is a major problem in most of LB versions.
=> Fix .reload

1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/command/commands/ScriptManagerCommand.kt
This fixes:
1. .scripts reload lagging for a short time after using the command for multiple times (same thing as with the .reload bug)
2. .scripts reload crashes
3. commands not working after executing
4. resetting values, states, binds of custom scripts
5. not updating clickgui
=> Fix .scripts reload

1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/PathUtils.java
The offset value of the original getPath() function is accidentally only a horizontal offset value; thus, if the current pos isn't on the same height as the target pos, the actual offside is bigger. Can cause the teleport not to work on servers because the real offset can exceed the max (vanilla) speed limit on servers even if the given offset value is low enough.
=> Fixed getPath() not considering Y offset

1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/exploit/Teleport.java
fixed teleport position not being displayed while setting when IgnoreNoCollision is disabled and you teleport onto a block without collision box.
(considered it when getting the actual teleport pos but not when sending the chat message (200 IQ))
=> fixed teleport position not being displayed

1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/misc/AntiBot.java
`Invalid` was misspelled as `Invaild` in UI and code.
=> Fixed typo in Antibot module

1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/player/Regen.kt
Regen timer overwrote other timer values even if timer is nolonger in "healing state".  (Was only an issue when Spartan mode was used once)
=> Fixed a timer bug in Regen

1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/combat/Ignite.java
"around" was misspelled as "aroung" in UI and code.
=> Fixed typo

1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/ModuleCommand.kt
Fixed a bug, where only the first found ListValue of a Module was "Tab-completed".
=> Fixed TabComplete Bug

1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/special/AutoReconnect.kt
When you turn auto-reconnect off and relaunch the client, the timer will be set to 60 seconds since `isEnabled` isn't defined correctly on start
=> Fixed AutoReconnect.isEnabled not defined correctly

1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/injection/backend/ClassProviderImpl.kt, shared/main/java/net/ccbluex/liquidbounce/features/module/modules/combat/Velocity.kt
#https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3903
It seemed that `isSPacketExplosion` should see if it is a `S27PacketExplosion` in 1.8.9.
Since all the `S12PacketEntityVelocity` was treated as explosion packets, it get canceled. 
```
if (classProvider.isSPacketExplosion(packet)) {
// TODO: Support velocity for explosions
event.cancelEvent()
}
```
Also 1.12 use
`override fun isSPacketExplosion(obj: Any?): Boolean = obj is PacketImpl<*> && obj.wrapped is SPacketEntityVelocity`
will cause the same problem.
It fixed the bug in 1.8.9, and it **_should_** fix the problem in 1.12.2
=> fixed isSPacketExplosion and possible problem in 1.12

.editorconfig, .github/CODING_STANDARDS.md
Add a .editorconfig to make it easier for developers to follow the correct code conventions regardless of which IDE they are using
=> chore: add .editorconfig

shared/main/java/net/ccbluex/liquidbounce/features/module/modules/movement/Speed.kt, shared/main/java/net/ccbluex/liquidbounce/features/module/modules/movement/speeds/other/Matrix.kt
* Could have been a lot better by adding strafes to it. I tried but it turned out wrong so I gave up and only did the speed part. As of the strafes module, it is easily detectable when on Matrix, but luckily there's a remade version of it by yorik100, which with that, you will probably have an even better advantage.
Speed tests, on 2 servers tested.
* Updated videos regarding the new updates.
* 11/25/2020:
* [Loyisa.](https://youtu.be/wKdbcmSRiQ8)
* [Tree server.](https://youtu.be/GUm6qMS023E)
=> Matrix Speed Addition.

shared/main/java/net/ccbluex/liquidbounce/features/module/modules/movement/speeds/aac/AAC3BHop.kt, shared/main/java/net/ccbluex/liquidbounce/features/module/modules/movement/speeds/aac/AAC5BHop.kt
* Fixes this [bug.](https://github.com/CCBlueX/LiquidBounce/issues/258)
I tested those 2 modes before fixing those, and I realized that when on AAC, it would flag for timer after running for a bit. After fixing these, I noticed that flags are gone.
=> Fixed AAC3Bhop/AAC5Bhop's Speed reset problems after being disabled.

shared/main/java/net/ccbluex/liquidbounce/features/module/modules/movement/Speed.kt, shared/main/java/net/ccbluex/liquidbounce/features/module/modules/movement/speeds/other/Matrix.kt
* Removed values and value sliders because they actually aren't that much useful. I mean like there's almost nothing to change that can make you go faster, so I went the way I originally wanted to and also improved the speed values.
* Also removed the movement reset when player would stop sprinting, bypasses a flag that way.
Hopefully these are my last speed changes because I feel like I'm spamming the [changelog](https://liquidbounce.net/download) with Matrix Speed changes.
=> Further Matrix Speed improvements.

shared/main/java/net/ccbluex/liquidbounce/utils/Rotation.kt
**Description**
LiquidBounce's mouse sensitivity repair is incorrect, yaw/pitch is not a multiple of gcd, but the **delta value of yaw/pitch** is a multiple of gcd. Fixing this bug can bypass AAC and some private anticheat, including my anticheat Matrix. Enjoy it~
**Why make this public?**
A hacked client in my country have already patched it and bypassed Matrix, so I don’t need to hide it anymore
The principle is explained below
=> A more correct rotation fix, which can bypass some advanced anti-cheats

src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/exploit/ModuleForceUnicodeChat.kt
This pull request will make ForceUnicodeChat do nothing if the chat message
starts with a slash, thus allowing for normal command functionality
while maintaining wide chat.
=>  Make ForceUnicodeChat work with commands
